/**
 * API Documentation
 * The API description
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PlayPositionLogListPostDto.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_PlayPositionLogListPostDto_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_PlayPositionLogListPostDto_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/Object.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  PlayPositionLogListPostDto
    : public ModelBase
{
public:
    PlayPositionLogListPostDto();
    virtual ~PlayPositionLogListPostDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// PlayPositionLogListPostDto members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Object> getPositions() const;
    bool positionsIsSet() const;
    void unsetPositions();

    void setPositions(const std::shared_ptr<Object>& value);


protected:
    std::shared_ptr<Object> m_Positions;
    bool m_PositionsIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_PlayPositionLogListPostDto_H_ */
